# Generated by Django 3.1 on 2020-10-11 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('mileage', models.CharField(max_length=50)),
                ('engine_capacity', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=50)),
                ('max_power', models.CharField(max_length=30)),
                ('max_speed', models.CharField(max_length=30)),
                ('torque', models.CharField(max_length=30)),
                ('fuel_consumption', models.CharField(max_length=30)),
                ('door', models.CharField(max_length=20)),
                ('drive_type', models.CharField(max_length=20)),
                ('seats', models.CharField(max_length=20)),
                ('wheel_base', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('fuel_tank_capacity', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('no_of_cylinder', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1024)),
                ('price', models.IntegerField()),
                ('showroom_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='main_images/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('v_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.category')),
            ],
        ),
        migrations.CreateModel(
            name='profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.IntegerField(blank=True, null=True)),
                ('selling', models.IntegerField(blank=True, null=True)),
                ('profitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vehicle_info')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/%Y/%m/%d')),
                ('imgID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vehicle_info')),
            ],
        ),
    ]
