# Generated by Django 3.1 on 2020-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_info',
            name='purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='selling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='profit',
        ),
    ]
