# Generated by Django 3.1 on 2020-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200929_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_info',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
