# Generated by Django 3.1 on 2020-10-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201012_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_info',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle_info',
            name='purchase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_info',
            name='selling',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
