# Generated by Django 3.1 on 2020-10-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201004_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_info',
            name='price',
            field=models.IntegerField(),
        ),
    ]
